// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// determine_lower_tri_indices
arma::uvec determine_lower_tri_indices(const arma::uvec& input, int noc_dist_mat);
RcppExport SEXP _DoD_determine_lower_tri_indices(SEXP inputSEXP, SEXP noc_dist_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type input(inputSEXP);
    Rcpp::traits::input_parameter< int >::type noc_dist_mat(noc_dist_matSEXP);
    rcpp_result_gen = Rcpp::wrap(determine_lower_tri_indices(input, noc_dist_mat));
    return rcpp_result_gen;
END_RCPP
}
// trimmed_quantile_diff
double trimmed_quantile_diff(const arma::vec sorted_distx, const arma::vec sorted_disty, double beta, double p);
RcppExport SEXP _DoD_trimmed_quantile_diff(SEXP sorted_distxSEXP, SEXP sorted_distySEXP, SEXP betaSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type sorted_distx(sorted_distxSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type sorted_disty(sorted_distySEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(trimmed_quantile_diff(sorted_distx, sorted_disty, beta, p));
    return rcpp_result_gen;
END_RCPP
}
// Bootstrap
arma::vec Bootstrap(int number, const double beta, const arma::mat& dist_sample, const int m, const arma::vec& sorteddist, const int p);
RcppExport SEXP _DoD_Bootstrap(SEXP numberSEXP, SEXP betaSEXP, SEXP dist_sampleSEXP, SEXP mSEXP, SEXP sorteddistSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type number(numberSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dist_sample(dist_sampleSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sorteddist(sorteddistSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(Bootstrap(number, beta, dist_sample, m, sorteddist, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DoD_determine_lower_tri_indices", (DL_FUNC) &_DoD_determine_lower_tri_indices, 2},
    {"_DoD_trimmed_quantile_diff", (DL_FUNC) &_DoD_trimmed_quantile_diff, 4},
    {"_DoD_Bootstrap", (DL_FUNC) &_DoD_Bootstrap, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DoD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
